// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF-VIYRKTUksSpBkpNvfEGcwDFnQTfzGw',
    appId: '1:750035518133:web:330cc7a363c30cdb6af4fc',
    messagingSenderId: '750035518133',
    projectId: 'step-forward-3e60d',
    authDomain: 'step-forward-3e60d.firebaseapp.com',
    storageBucket: 'step-forward-3e60d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1pkWbF6LnP4okxv_PUo0_ryJkDaEPOzk',
    appId: '1:750035518133:android:d578fde87832d4f56af4fc',
    messagingSenderId: '750035518133',
    projectId: 'step-forward-3e60d',
    storageBucket: 'step-forward-3e60d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3CApxwCKDqr9wIDUjCo8qXqIkIvv3JD4',
    appId: '1:750035518133:ios:511ec47caca1851a6af4fc',
    messagingSenderId: '750035518133',
    projectId: 'step-forward-3e60d',
    storageBucket: 'step-forward-3e60d.appspot.com',
    iosBundleId: 'com.example.stepForward',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3CApxwCKDqr9wIDUjCo8qXqIkIvv3JD4',
    appId: '1:750035518133:ios:a86081e3690d852d6af4fc',
    messagingSenderId: '750035518133',
    projectId: 'step-forward-3e60d',
    storageBucket: 'step-forward-3e60d.appspot.com',
    iosBundleId: 'com.example.stepForward.RunnerTests',
  );
}
